### ISSUE TITLE
PID settings UART communication problem 

### ISSUE THREAD

**Issue by bojfik** [ottoragam/Tarocco#18]
https://youtu.be/Y-sH2tY315Y

Please watch the video showing the problem, I cannot describe it.  Programming via UART via FTDI without any problems.  Then the problem with the PID setting
Everything is done as in the manual. Uploaded bootloader using CY8CKIT-059 - no problems, then uploaded firmware via UART also without any problems. I started this set and the motor keeps torque, you can't move it with your fingers so the pcb works. After starting Termite to set the PID, what you see in the movie happens. baudrate set to 19200, data bits 8, no parity bits, one stop bit. It does not work.

**Comment by ottoragam** [comment]
Hi @bojfik I'll check the video in a bit and report back.

**Comment by bojfik** [comment]
> Hi @bojfik I'll check the video in a bit and report back.

OK thanks.  I will just add that the bootloader is cncboot.cydsn and the firmware is those from 2017-08-12

**Comment by bojfik** [comment]
> Hi @bojfik I'll check the video in a bit and report back.

More explain on this video
https://youtu.be/0OufBB6x35c
Sorry for my bad english

**Comment by bojfik** [comment]
I took another CNC PCB and reprogrammed the bootloader and uploaded the firmware sequentially.  without any changes, bootloader loads correctly, firmware too, but I still don't have access to PID settings. the firmware in your github is bad

**Comment by ottoragam** [comment]
Hey, sorry for the lapse in communication, I was kinda busy until yesterday. I saw both videos and it appears your setup is working fine. I just think there is a bit of confusion regarding the motor tuning. Let me explain:

What you're seeing on the terminal ($00500; $00510;) is the board streaming both the following error and the motor current. In this case the error is 0 because the motor is not moving yet and the current is 500 mA. You can use a program like https://github.com/CieNTi/serial_port_plotter/releases to watch the plots in real time to help with motor tuning.

In order to tune the P, I, D coefficients, you need to use a terminal program (my choice is Realterm, as it allows you to hide the data stream from the Tarooco, but anything should work) and type something like p5000;

I suggest to try the Serial Port Plotter software while moving the motor shaft by hand to get a feeling on how the updated coefficients change the motor behaviour.

Let me know if you need more help.

**Comment by bojfik** [comment]
Thank you very much for your answer.  I thought what I see in the terminal is a communication error 😁 now I understand everything.I'll check it tomorrow, now it's 23:26 pm at my place

**Comment by ottoragam** [comment]
No problem! Hit me up again if something else comes up.
